#!/bin/sh
SCRIPTS_FOLDER=$HOME/.local/bin/scripts
if test -d $SCRIPTS_FOLDER
then
	mv ./bin/* $SCRIPTS_FOLDER
	echo "Binaries successfully moved to $SCRIPTS_FOLDER"
else
	echo "$SCRIPTS_FOLDER is not a directory! Change the $SCRIPTS_FOLDER variable."
fi
